name = "slizebiz-landing"
compatibility_date = "2024-11-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "slizebiz-waitlist"
database_id = "fc76ff99-d167-4570-a8ae-58923ab31e4d"
